apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.workloadClusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "{{ .Values.projectStateStoreBucket }}"
          key      = "registry/clusters/{{ .Values.workloadClusterName }}/infrastructure/provider-config/terraform.tfstate"
          region = "{{ .Values.projectClusterRegion }}"
          encrypt = true
        }
        required_providers {
          kubernetes = {
            source = "hashicorp/kubernetes"
            version = ">= 2.23.0, < 3.0.0"
          }
          vault = {
            source = "hashicorp/vault"
            version = ">= 3.19.0, < 4.0.0"
          }
          random = {
            source = "hashicorp/random"
            version = ">= 3.6.2, < 4.0.0"
          }
          aws = {
            source = "hashicorp/aws"
            version = ">= 5.30.0, < 6.0.0"
          }
        }
      }
      provider "aws" {
        region = "{{ .Values.workloadClusterRegion }}"
        allowed_account_ids = ["{{ .Values.workloadClusterAccountId }}"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "{{ .Values.workloadAssumeRole }}"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
      provider "aws" {
        alias  = "project_cluster_region"
        region = "{{ .Values.projectClusterRegion }}"
        allowed_account_ids = ["{{ .Values.projectClusterAwsAccountId }}"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "{{ .Values.projectClusterAssumeRole }}"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
      provider "aws" {
        alias = "kubefirst_mgmt_region"
        region = "{{ .Values.cloudRegion }}"
        allowed_account_ids = ["{{ .Values.kubefirstMgmtAccountId }}"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "arn:aws:iam::{{ .Values.kubefirstMgmtAccountId }}:role/crossplane-{{ .Values.projectClusterName }}"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
  pluginCache: false
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: no-creds
      key: token
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
